"""security_add_otp_fields_to_user

Revision ID: 0365dbc64f46
Revises: 747f7bc41787
Create Date: 2026-09-28 19:37:07.595659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0365dbc64f46'
down_revision: Union[str, Sequence[str], None] = '747f7bc41787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('preferred_currency', sa.String(), nullable=True))
    op.add_column('users', sa.Column('allows_local_meetup', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('allows_nationwide_shipping', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('otp_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('otp_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('completed_trades', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('disputes_count', sa.Integer(), nullable=True))
    op.drop_column('users', 'verification_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'disputes_count')
    op.drop_column('users', 'completed_trades')
    op.drop_column('users', 'rating')
    op.drop_column('users', 'otp_attempts')
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp_hash')
    op.drop_column('users', 'allows_nationwide_shipping')
    op.drop_column('users', 'allows_local_meetup')
    op.drop_column('users', 'preferred_currency')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'location')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
