"""initial_schema

Revision ID: 747f7bc41787
Revises: 
Create Date: 2026-09-27 18:44:46.409166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747f7bc41787'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('set', sa.String(), nullable=True),
    sa.Column('type_line', sa.String(), nullable=True),
    sa.Column('mana_cost', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('scryfall_raw_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartas_id'), 'cartas', ['id'], unique=False)
    op.create_index(op.f('ix_cartas_name'), 'cartas', ['name'], unique=False)
    op.create_index(op.f('ix_cartas_set'), 'cartas', ['set'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_code', sa.String(), nullable=True),
    sa.Column('reputation_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('decks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decks_user_id'), 'decks', ['user_id'], unique=False)
    op.create_table('historico_precios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scryfall_card_id', sa.String(), nullable=False),
    sa.Column('tienda', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('precio_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['scryfall_card_id'], ['cartas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scryfall_card_id', 'tienda', 'tipo', 'fecha', name='uq_historico_carta_tienda_fecha')
    )
    op.create_index('idx_historico_carta_fecha', 'historico_precios', ['scryfall_card_id', 'fecha'], unique=False)
    op.create_index(op.f('ix_historico_precios_scryfall_card_id'), 'historico_precios', ['scryfall_card_id'], unique=False)
    op.create_table('wishlist_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('scryfall_card_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scryfall_card_id'], ['cartas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlist_items_scryfall_card_id'), 'wishlist_items', ['scryfall_card_id'], unique=False)
    op.create_index(op.f('ix_wishlist_items_user_id'), 'wishlist_items', ['user_id'], unique=False)
    op.create_table('deck_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deck_id', sa.String(), nullable=False),
    sa.Column('scryfall_card_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['scryfall_card_id'], ['cartas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_cards_deck_id'), 'deck_cards', ['deck_id'], unique=False)
    op.create_index(op.f('ix_deck_cards_scryfall_card_id'), 'deck_cards', ['scryfall_card_id'], unique=False)
    op.create_table('user_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('scryfall_card_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('is_foil', sa.Boolean(), nullable=True),
    sa.Column('is_for_trade', sa.Boolean(), nullable=True),
    sa.Column('trade_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['scryfall_card_id'], ['cartas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cards_collection_id'), 'user_cards', ['collection_id'], unique=False)
    op.create_index(op.f('ix_user_cards_is_for_trade'), 'user_cards', ['is_for_trade'], unique=False)
    op.create_index(op.f('ix_user_cards_scryfall_card_id'), 'user_cards', ['scryfall_card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_cards_scryfall_card_id'), table_name='user_cards')
    op.drop_index(op.f('ix_user_cards_is_for_trade'), table_name='user_cards')
    op.drop_index(op.f('ix_user_cards_collection_id'), table_name='user_cards')
    op.drop_table('user_cards')
    op.drop_index(op.f('ix_deck_cards_scryfall_card_id'), table_name='deck_cards')
    op.drop_index(op.f('ix_deck_cards_deck_id'), table_name='deck_cards')
    op.drop_table('deck_cards')
    op.drop_index(op.f('ix_wishlist_items_user_id'), table_name='wishlist_items')
    op.drop_index(op.f('ix_wishlist_items_scryfall_card_id'), table_name='wishlist_items')
    op.drop_table('wishlist_items')
    op.drop_index(op.f('ix_historico_precios_scryfall_card_id'), table_name='historico_precios')
    op.drop_index('idx_historico_carta_fecha', table_name='historico_precios')
    op.drop_table('historico_precios')
    op.drop_index(op.f('ix_decks_user_id'), table_name='decks')
    op.drop_table('decks')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cartas_set'), table_name='cartas')
    op.drop_index(op.f('ix_cartas_name'), table_name='cartas')
    op.drop_index(op.f('ix_cartas_id'), table_name='cartas')
    op.drop_table('cartas')
    # ### end Alembic commands ###
